sf_archery_sports_manager:
    resource: "@SfArcherySportsManagerBundle/Resources/config/routing.yml"
    prefix:   /archerySportsManager

app:
    resource: '@AppBundle/Controller/'
    type: annotation
