home:
    path:     /
    defaults: { _controller: SfArcherySportsManagerBundle:Default:index }

security_logout:
    path:     /logout
    defaults: { _controller: SfArcherySportsManagerBundle:Security:logout }

security_login:
    path:     /login
    defaults: { _controller: SfArcherySportsManagerBundle:Security:login }

backoffice_homepage:
    path:     /dashboard
    defaults: { _controller: SfArcherySportsManagerBundle:Default:index }
