services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Sf\ArcherySportsManagerBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository}'

