<?php

namespace Sf\ArcherySportsManagerBundle\Repository;
use Sf\ArcherySportsManagerBundle\Entity\Saison;

/**
 * ArcherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArcherRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArchersFromSaison(Saison $saison){
        return $this->createQueryBuilder('a')
            ->join('a.departs','d')
            ->join('d.concours','c')
            ->join('d.resultat','r')
            ->andWhere('c.saison = :saison')
            ->setParameter('saison',$saison->getId())
            ->getQuery()
            ->getResult()
            ;
    }
}
