<?php

namespace Sf\ArcherySportsManagerBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * DepartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartRepository extends EntityRepository
{
}
