<?php

namespace Sf\ArcherySportsManagerBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Sf\ArcherySportsManagerBundle\Entity\Saison;

/**
 * DepartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartRepository extends EntityRepository
{
    public function getNbDepartsForSaison(Saison $saison){
        return $this->createQueryBuilder('d')
            ->select('count(d.id)')
            ->join('d.concours','c')
            ->andWhere('c.saison = :saison')
            ->setParameter('saison',$saison->getId())
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }

}
