<?php
/**
 * Created by PhpStorm.
 * User: floste
 * Date: 22/06/2018
 * Time: 22:34
 */

namespace Sf\ArcherySportsManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ResultRepository extends EntityRepository
{

}